services:
  - type: web
    name: muud-prototype
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: node src/prototype.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
